Review #1
aleoreh/blog-customizer pull request #1
Opened 2024-04-22 11:47 UTC by aleoreh

2024-04-22 21:08 UTC, olgalatkina requested changes
Добрый день!

**У вас получилась хорошая работа:**
1. Полностью реализован весь функционал.
2. Проект соответствует макету на сколько это возможно.
3. Для условного добавления css-классов спользуется библиотека `clsx`.
4. Логика закрытия сайдбара по клику вне сайдбара вынесена в кастомный хук.
5. Обработчик сохранения данных вызывается при отправке формы.

**Но есть несколько моментов, которые надо поправить:**
- [ ] Компонент страницы не должен знать про состояние формы. Состояние формы надо перенести в компонент `ArticleParamsForm`. Туда же нужно перенести все обработчики.
- [ ] Не нужно создавать компонент `InputArticleParams` и переменную `defaultStyle`
- [ ] В проекте как настройки по умолчанию нужно использовать значения из объекта `defaultArticleState`
- [ ] Исправить кастомный хук, чтобы обработчик закрытия по клику вне сайдбара  навешивался при его открытии и удалялся при закрытии.
 
**Правки можно лучше остаются на ваше усмотрение:**
- [ ] Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.
- [ ] Для одиночных селекторов не стоит использовать библиотеку `clsx `(см. компоненты `Article` и `App`).
- [ ] Попробуйте обойтись без лишней обёртки `toggleOpen` над функцией-сеттером
- [ ] Используйте деструктуризацию пропсов сразу в параметрах компонента
 
Успешного рефакторинга!

2024-04-22 21:08 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +.form_spacing {
**Можно лучше:**
В этой проектной работе нет необходимости писать дополнительный css-класс. Свойство `gap` просто добавляем в класс `.form`.

2024-04-22 21:08 UTC, olgalatkina commented on src/index.tsx
> +	const [articleStyle, setArticeStyle] = useState<ArticleStyle>(defaultStyle);
**Надо исправить:** 
Настройки статьи по умолчанию описаны в объекте `defaultArticleState`  в файле `constants/articleProps.ts` стартеркита. В проекте нужно использовать значения из этого объекта как настройки по умолчанию, как для самой статьи, так и как начальные значения полей форм.

2024-04-22 21:08 UTC, olgalatkina commented on src/types.ts
> +export type ArticleStyle = {
**Надо исправить:** 
В проекте как настройки по умолчанию нужно использовать значения из объекта `defaultArticleState`. Этот тип стоит удалить как неиспользуемый.

2024-04-22 21:08 UTC, olgalatkina commented on src/index.tsx
>  const App = () => {
Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-04-22 21:08 UTC, olgalatkina commented on src/index.tsx
> +	const [inputArticleStyle, setInputArticleStyle] =
**Надо исправить:** 
Каждый компонент сам должен отвечать за хранение и обработку своего состояния. Использовать подъем состояния в родительский компонент не имеет смысла для нашего приложения. Состояние формы нужно описать в самом компонент `ArticleParamsForm`, а не передавать его из `App`, т.к. это состояние описывает именно `ArticleParamsForm`. В состоянии `App` должны хранится только данные о текущем отображении статьи.

2024-04-22 21:08 UTC, olgalatkina commented on src/index.tsx
> +	const [articleParamsFormOpened, setArticleParamsFormOpened] =
**Надо исправить:**
1. Обычно переменные, которые сохраняют булево значение начинаются с глагола `is` или `has`, например, `isOpen`
2. Это состояние тоже нужно перенести в компонент `ArticleParamsForm` вместе обработчиками отправки и сброса формы.

2024-04-22 21:08 UTC, olgalatkina commented on src/index.tsx
> +const defaultStyle: ArticleStyle = {
**Надо исправить:**
В проекте как настройки по умолчанию нужно использовать значения из объекта `defaultArticleState`. Этот объект стоит удалить как неиспользуемый.

2024-04-22 21:08 UTC, olgalatkina commented on src/index.tsx
> +				<InputArticleParams
**Надо исправить:**
Поля формы это часть компонента `ArticleParamsForm`, отвечающего за настройки отображения статьи и не предусмотрено, что в форму будет передаваться разный набор полей ввода. 
В этой проектной работе всё наполнение формы прописываем в компоненте `ArticleParamsForm`. Просто собираем её из готовых компонентов. Компонент `InputArticleParams` не понадобится.

2024-04-22 21:08 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					onSubmit={submitForm}
**Отлично:**
Отлично, что обработчик сохранения данных вызывается при отправке формы.

2024-04-22 21:08 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const submitForm = (evt: React.FormEvent) => {
**Можно лучше:**
`React.FormEvent<HTMLFormElement>`

2024-04-22 21:08 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +export const ArrowButton = forwardRef<HTMLDivElement, ArrowButtonProps>(
**Нужно исправить:**
Использование `forwardRef` избыточно. Достаточно передать флаг открытости/закрытости сайдбара и функцию меняющую этот флаг.

2024-04-22 21:08 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +				className={clsx(
**Отлично:**
Здорово, что используете библиотеку `clsx`.

2024-04-22 21:08 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +	(props: ArrowButtonProps, ref) => {
**Можно лучше:** 
Можно использовать деструктуризацию пропсов сразу в параметрах компонента, это распространенная практика.

2024-04-22 21:08 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const toggleOpen = () => {
**Можно лучше:** 
Нет необходимости создавать дополнительные функции обработчики если они сами по себе ничего не делают, можно использовать просто функции сеттеры возвращаемые `useState`.

2024-04-22 21:08 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const containerRef = useRef<HTMLElement>(null);
**Нужно исправить:**
Реф инициализируется значением `null`, поэтому типизация будет выглядеть так:
```
const containerRef = useRef<HTMLElement | null>(null);
```

2024-04-22 21:08 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +export const ArticleParamsForm = (props: ArticleParamsFormProps) => {
**Можно лучше:**
Можно использовать деструктуризацию пропсов сразу в параметрах компонента, это распространенная практика.

2024-04-22 21:08 UTC, olgalatkina commented on src/hooks/useOutsideClick.ts
> +		window.addEventListener('click', handleClick);
**Можно лучше:**
Используйте событие `mousedown` и тогда не придётся использовать `evt.stopPropagation()` у компонента `ArrowButton`. 
Таким же образом стоит "починить" хук `useOutsideClickClose` в компоненте `Select`.

**Отлично:**
Здорово, что вы вынесли логику закрытия сайдбара по клику вне сайдбара в кастомный хук.
Можете попробовать другое готовое решение, в нём так же реализовано закрытие по `Escape`:
```
import { useEffect } from "react";

type TUseClose = {
  isOpen: boolean;
  onClose: () => void;
  rootRef: React.RefObject<HTMLElement>;
};

// Кастомные хуки всегда должны начинаться с глагола `use`, чтобы реакт понял, что это хук. 
// Он следит за их вызовами
export function useClose({isOpen, onClose, rootRef}: TUseClose) {
  useEffect(() => {
    if (!isOpen) return; // останавливаем действие эффекта, если закрыто
   
    function handleClickOutside(event: MouseEvent) {
      const { target } = event;
      
      const isOutsideClick =
        target instanceof Node && // проверяем, что это `DOM`-элемент
        rootRef.current &&
        !rootRef.current.contains(target); // проверяем, что кликнули на элемент, который находится не внутри блока
      if (isOutsideClick) {
        onClose();
      }
    }

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        onClose();
      }
    };

    document.addEventListener("keydown", handleEscape);
    document.addEventListener("mousedown", handleClickOutside);

    //  Обязательно удаляем обработчики в `clean-up`- функции
    return () => {
      document.removeEventListener("keydown", handleEscape);
      document.removeEventListener("mousedown", handleClickOutside);
    };
    
    // Обязательно следим за `isOpen`, чтобы срабатывало только при открытии, 
    // а не при любой перерисовке компонента
  }, [isOpen, onClose, rootRef]);
}
```

Этот код помещают в отдельный файл `useClose.ts` в папке `hooks` (она у вас уже создана) и импортируют хук туда, где нужно.
Теперь его можно использовать в любом компоненте (попапе, меню и тд), которому нужно установить эти обработчики.

Пример того, как это использовать:
```
    // Создаем `ref` для формы и указываем его на внешнем блоке с формой
    const formRef = useRef<HTMLElement | null>(null);
    
    useClose({
        isOpen,
        onClose: () => setIsOpen(false),
        rootRef: formRef,
    }); 
```

2024-04-22 21:08 UTC, olgalatkina commented on src/hooks/useOutsideClick.ts
> +	useEffect(() => {
**Надо исправить:** 
Обработчик не должен висеть всегда на документе, его нужно вешать в момент открытия и удалять в момент закрытия. Нет необходио отслеживать событие, если сайдбар закрыт. Поэтому необходимо указать массив зависимостей хука `useEffect` и добавить внутри проверку, что сайдбар открыт. 
Чтобы это реализовать, вам понадобится передать в хук флаг `isOpen`.

2024-04-22 21:08 UTC, olgalatkina commented on src/components/input-article-params/InputArticleParams.tsx
> +				onChange={onFontSelected}
**Можно лучше:** 
Если для каждого поля ввода формы создается свой обработчик событий, то удобнее хранить все данные формы в одном стейте.
```
	const [formState, setFormState] = useState(defaultArticleState);

	const handleChange = (type: keyof ArticleStateType, value: OptionType) => {
		setFormState({
			...formState,
			[type]: value
		})
	};
	```

2024-04-22 21:08 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					ev.stopPropagation();
**Можно лучше:** 
Для параметра являющегося событием общеупотребимым сокращением названия является `evt` или `e` лучше придерживаться этого имени.

2024-04-23 04:30 UTC, aleoreh commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +.form_spacing {
Старался не затрагивать изначальный код. Исправлено

2024-04-23 06:05 UTC, aleoreh commented on src/index.tsx
> +	const [inputArticleStyle, setInputArticleStyle] =
Исправлено вместе с избавлением от InputArticleParams

2024-04-23 06:08 UTC, aleoreh commented on src/index.tsx
> +const defaultStyle: ArticleStyle = {
Исправлено вместе с "Переключает состояние по умолчанию"

2024-04-23 07:22 UTC, aleoreh commented on src/hooks/useOutsideClick.ts
> +		window.addEventListener('click', handleClick);
Реализовал хук useModalClose с отработкой mousedown и keydown

2024-04-23 19:20 UTC, olgalatkina requested changes
Отличная работа!

**Осталось исправить совсем немного:**
- [ ] Перенести обработчики событий формы в `ArticleParamsForm`
- [ ] Поправить кастомный хук

**Можно лучше:**
Стоит перенести реф на внешний `div`.

Успешного рефакторинга!

2024-04-23 19:20 UTC, olgalatkina commented on src/components/app/App.tsx
> +	const submitArticleParamsForm = (articleState: ArticleStateType) => {
**Надо исправить:**
Не исправлено замечание с прошлого ревью: обработчики событий формы `submitArticleParamsForm` и `onArticleParamsFormReset` надо перенести в компонент `ArticleParamsForm`. Страница ничего не должна знать про форму и её события. В вашем решении в компонент `ArticleParamsForm` достаточно пробросить функцию-сеттер, возвращаемую хуком `useState`. 

В React ссылка на функцию-сеттер, возвращаемую хуком `useState`, обычно является стабильной. Это означает, что она будет оставаться той же самой функцией при каждом рендере компонента.

2024-04-23 19:20 UTC, olgalatkina commented on src/hooks/useModalClose.ts
> +		const normalizedSelfRefs = Array.isArray(selfRefs) ? selfRefs : [selfRefs];
**Надо исправить:**
Вряд ли здесь может оказаться массив. Стоит исправить этот момент.

2024-04-23 19:20 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +				ref={containerRef}
**Можно лучше:**
Если реф перенести на внешний `div`, то баг с кнопкой уйдёт. `div` будет на месте `React.Fragment`. Не забудьте протипизировать хук `useRef`.

2024-04-24 12:22 UTC, olgalatkina approved these changes
Добрый день!

**Отличная работа! проект принимается**🎉

Успехов в дальнейшем обучении!

2024-04-24 12:37 UTC, merged